import React,{useEffect,useState} from "react"; import {createRoot} from "react-dom/client"; import axios from "axios"; import {io} from "socket.io-client"; import {BookOpen,BarChart3,Bell,CheckCircle,LogOut,PlayCircle,ShieldCheck,Target} from "lucide-react"; import "./index.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:5000/api";
axios.defaults.baseURL=API;
type Course={id:string;title:string;description:string;difficulty:string;category:string;lessons:any[];assessments:any[]};
function App(){
 const [token,setToken]=useState(localStorage.getItem("token")); const [user,setUser]=useState<any>(JSON.parse(localStorage.getItem("user")||"null")); const [courses,setCourses]=useState<Course[]>([]); const [dash,setDash]=useState<any>(null); const [login,setLogin]=useState(false);
 const load=async()=>{setCourses((await axios.get("/courses")).data); if(token) setDash((await axios.get("/dashboard",{headers:{Authorization:`Bearer ${token}`}})).data)};
 useEffect(()=>{load()},[token]);
 useEffect(()=>{if(token&&user){const s=io(API.replace("/api",""));s.emit("join",user.id);s.on("notification",(n:any)=>alert(n.message));return()=>{s.disconnect()}}},[token,user]);
 if(!token) return <Login onLogin={(t,u)=>{localStorage.setItem("token",t);localStorage.setItem("user",JSON.stringify(u));setToken(t);setUser(u)}} />;
 const logout=()=>{localStorage.clear();setToken(null);setUser(null)};
 return <div className="min-h-screen">
  <header className="bg-slate-950 text-white"><div className="max-w-6xl mx-auto px-6 py-5 flex justify-between items-center"><div className="flex gap-3 items-center font-black text-xl"><div className="bg-indigo-500 p-2 rounded-xl"><BookOpen size={20}/></div>LearnSphere AI</div><div className="flex items-center gap-5 text-sm"><span className="text-slate-300">Learning Intelligence Platform</span><button onClick={logout} className="btn bg-white text-slate-900 flex gap-2"><LogOut size={16}/>Logout</button></div></div></header>
  <main className="max-w-6xl mx-auto px-6 py-8">
   <div className="mb-8"><p className="text-indigo-600 font-bold">STUDENT DASHBOARD</p><h1 className="text-3xl font-black mt-1">Welcome back, {user?.name} 👋</h1><p className="text-slate-500 mt-2">Build skills. Practice. Measure progress.</p></div>
   {dash&&<><div className="grid md:grid-cols-3 gap-5 mb-8"><Stat icon={<Target/>} label="Assessments" value={dash.stats.assessments}/><Stat icon={<BarChart3/>} label="Average Score" value={`${dash.stats.average}%`}/><Stat icon={<CheckCircle/>} label="Courses Started" value={dash.stats.courses}/></div>
   <section className="card mb-8"><div className="flex justify-between"><h2 className="font-black text-xl">Your Skill Progress</h2><span className="text-sm text-slate-500">{dash.progress[0]?Math.round(dash.progress[0].percent):0}% overall</span></div><div className="h-3 bg-slate-100 rounded-full mt-4 overflow-hidden"><div className="h-full bg-indigo-600" style={{width:`${dash.progress[0]?.percent||0}%`}}/></div></section></>}
   <h2 className="font-black text-2xl mb-4">Recommended Learning</h2><div className="grid md:grid-cols-2 gap-5">{courses.map(c=><div className="card" key={c.id}><div className="flex justify-between"><span className="text-xs font-bold bg-indigo-50 text-indigo-700 px-3 py-1 rounded-full">{c.category}</span><span className="text-xs text-slate-500">{c.difficulty}</span></div><h3 className="text-xl font-black mt-4">{c.title}</h3><p className="text-slate-500 mt-2">{c.description}</p><div className="flex gap-3 mt-5"><button onClick={async()=>{const a=c.assessments[0];if(a){const r=await axios.get(`/assessments/${a.id}`,{headers:{Authorization:`Bearer ${token}`}});alert(`Assessment: ${r.data.title}\\n${r.data.questions.length} questions\\n${r.data.duration} minutes\\n\\nYou can extend this demo into a full assessment UI.`)}}} className="btn bg-indigo-600 text-white flex gap-2"><PlayCircle size={17}/>Take Assessment</button><span className="text-sm text-slate-500 flex items-center">{c.lessons.length} lessons</span></div></div>)}</div>
   <section className="grid md:grid-cols-2 gap-5 mt-8"><div className="card"><h2 className="font-black text-lg flex gap-2"><ShieldCheck size={20}/>Engineering Practices</h2><p className="text-slate-500 mt-2">REST APIs, validation, PostgreSQL indexes, migrations, Docker and CI/CD are included in the backend architecture.</p></div><div className="card"><h2 className="font-black text-lg flex gap-2"><Bell size={20}/>Real-time Notifications</h2><p className="text-slate-500 mt-2">Socket.IO events notify students when assessments are submitted or milestones are reached.</p></div></section>
  </main></div>
}
function Stat({icon,label,value}:any){return <div className="card flex gap-4 items-center"><div className="p-3 rounded-xl bg-indigo-50 text-indigo-600">{icon}</div><div><div className="text-slate-500 text-sm">{label}</div><div className="text-2xl font-black">{value}</div></div></div>}
function Login({onLogin}:any){const [register,setRegister]=useState(false);const [form,setForm]=useState({name:"",email:"demo@learnsphere.dev",password:"Password123!"});const submit=async(e:any)=>{e.preventDefault();try{const r=await axios.post(`/auth/${register?"register":"login"}`,form);onLogin(r.data.token,r.data.user)}catch(e:any){alert(e.response?.data?.message||"Request failed")}};return <div className="min-h-screen flex items-center justify-center p-6 bg-slate-950"><div className="bg-white rounded-3xl p-8 w-full max-w-md"><div className="text-center"><div className="inline-flex p-3 rounded-2xl bg-indigo-600 text-white"><BookOpen/></div><h1 className="text-3xl font-black mt-4">LearnSphere AI</h1><p className="text-slate-500 mt-2">Full-stack learning intelligence platform</p></div><form onSubmit={submit} className="mt-8 space-y-4">{register&&<input className="w-full border p-3 rounded-xl" placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input className="w-full border p-3 rounded-xl" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="w-full border p-3 rounded-xl" type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button className="btn bg-indigo-600 text-white w-full">{register?"Create account":"Sign in"}</button></form><button className="w-full mt-4 text-indigo-600 font-bold" onClick={()=>setRegister(!register)}>{register?"Already have an account? Sign in":"Create a new account"}</button><p className="text-xs text-center text-slate-400 mt-6">Demo: demo@learnsphere.dev / Password123!</p></div></div>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
